(function(g){var window=this;'use strict';var B3=function(a){a.publish("cardstatechange",a.Wk()&&a.Dp()?1:0)},C3=function(a,b){var c=g.bb(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},Fqb=function(a){var b=g.Us(a);
a=g.Xs(a);return new g.Is(b.x,b.y,a.width,a.height)},Gqb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.fB(a,b,function(){g.gB(e);c.apply(a,arguments)},d)},F3=function(a){a=g.fb(a);
delete D3[a];g.gd(D3)&&E3&&E3.stop()},Iqb=function(){E3||(E3=new g.uv(function(){Hqb()},20));
var a=E3;a.isActive()||a.start()},Hqb=function(){var a=g.kb();
g.Tc(D3,function(b){Jqb(b,a)});
g.gd(D3)||Iqb()},G3=function(a,b,c,d){g.Gv.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Jqb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Kqb(a,a.progress);a.progress==1?(a.j=0,F3(a),a.onFinish(),a.qs()):a.isPlaying()&&a.VM()},Kqb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Lqb=function(a,b){g.yb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},H3=function(a,b,c,d,e){G3.call(this,b,c,d,e);
this.element=a},Mqb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
H3.call(this,a,b,c,d,e)},Nqb=function(a){return Math.pow(a,3)},Oqb=function(a){return 3*a*a-2*a*a*a},Pqb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},I3=function(a){return a.baseUrl||null},J3=function(a,b){return g.Pt(g.cs(a,b),function(c){return!!c})},Qqb=function(a,b,c){function d(qa){var ha=qa.hovercardButton;
if(!ha)return null;ha=ha.subscribeButtonRenderer;if(!ha)return null;var ta=f(ha.unsubscribedButtonText),P=f(ha.subscribedButtonText);if(ha.subscribed){var ua=f(ha.subscriberCountWithUnsubscribeText);var y=f(ha.subscriberCountText)}else ua=f(ha.subscriberCountText),y=f(ha.subscriberCountWithSubscribeText);var Z=null;if(qa.signinEndpoint){Z=C3(qa,"signinEndpoint","webNavigationEndpointData","url");if(!Z){var cb,La;Z=(La=g.V((cb=ha.signInEndpoint)==null?void 0:cb.commandMetadata,g.u2))==null?void 0:
La.url}if(!Z)return null}return ta&&(P||Z)?{subscribed:ha.subscribed,subscribeText:ta,subscribeCount:ua,unsubscribeText:P,unsubscribeCount:y,enabled:ha.enabled,signinUrl:Z,classic:qa.useClassicSubscribeButton}:null}
function e(qa){if(qa){var ha=[],ta=qa.videoId;ta&&ha.push("v="+ta);(ta=qa.playlistId)&&ha.push("list="+ta);(qa=qa.startTimeSeconds)&&ha.push("t="+qa);return"/watch?"+ha.join("&")}}
function f(qa){if(!qa)return null;var ha=qa.simpleText;return ha?ha:qa.runs?g.cs(qa.runs,function(ta){return ta.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,w=!1,A=null,C=null,F=null,H=null,M=null,N=null;if(h==="VIDEO")g.V(l,g.VE)?m=g.V(l,g.VE).url:(N=g.V(l,g.AS),m=e(N)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.V(l,g.VE)?m=g.V(l,g.VE).url:(N=g.V(l,g.AS),m=e(N)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(w=C3(l,"browseEndpoint","browseId"))u=w,m="/channel/"+u;n=!1;q="new";(w=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((F=C3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(M=f(b.additionalFeesText)),(n=C3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=C3(b,"title","accessibility","accessibilityData","label");var Q=b.endpoint?b.endpoint.clickTrackingParams:
null,da="";if(b.metadata){var na=f(b.metadata);na&&(da=na)}return{id:"element-"+c,type:h,title:f(b.title),metadata:da,callToAction:f(b.callToAction),HX:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,uF:p,playlistLength:t,channelId:u,subscribeButton:A,subscribersText:C,isSubscribe:w,targetUrl:m||null,p$:n,sessionData:Q?{itct:Q}:null,Jea:q,RD:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:J3(b.impressionUrls||[],I3),e$:J3(b.hovercardShowUrls||[],I3),clickUrls:J3(l.loggingUrls||[],I3),visualElement:g.ZD(b.trackingParams),productPrice:H,additionalFeesText:M,watchEndpoint:N||null}},Rqb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:J3(a.impressionUrls||[],I3),elements:J3(a.elements||[],function(d,e){return Qqb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.ZD(a.trackingParams));return c},Sqb=function(a){g.dV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.oR(a)||g.qR(a);this.events=new g.GJ(this);g.L(this,this.events);this.events.T(this.player,g.MI("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.NI("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.lc);this.events.T(window,"focus",this.Qca);this.load();var b=g.Bf("STYLE");(g.of("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Mf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Tqb=function(a){return a.player.getVideoData().Kf?"current":a.Z?"new":"current"},K3=function(a){return a.player.U().playerStyle==="creator-endscreen-editor"},Uqb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=Rqb(f,Tqb(a))));L3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.dw;d&&(c.postParams={ad_tracking:d});if(b=g.hYa(b))if(b=g.je(b),b=g.de(b))a.C=g.yA(b,c)},L3=function(a,b,c){c=c===void 0?!0:c;
a.player.tf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.v(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.N.length>0&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Vqb(a);c=[];d=new g.LI(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.W({I:"div",S:"ytp-ce-shadow"}),g.ET(a.player,a.B.element,4),a.D=new g.iF(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Wqb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.ET(a.player,f.element,4);var h=new g.LI(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Xqb(a,f,e)}else g.eE(new g.wB("buildEndscreenElement null",
e))}a.player.mf(c);a.lc()}},Vqb=function(a){var b=g.$D(),c=g.aE();
c&&b&&a.endscreen.visualElement&&g.eA(g.nE)(void 0,c,b,a.endscreen.visualElement)},Wqb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ka:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.RD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:M3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:N3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.Jv(b.title||"")},va:b.title},{I:"div",S:b.uF?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
va:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={I:"div",Ka:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.RD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:M3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:N3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ka:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.Jv(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={I:"div",Ka:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.RD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ka:["ytp-ce-channel-title","ytp-ce-link"],W:{href:N3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Jv(b.title||"")},va:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{I:"div",Ka:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:M3(b)}]};c=new g.W(c);var d=g.pf(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Bv(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.UV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ka:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.RD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",W:{dir:g.Jv(b.title||"")},va:b.title},{I:"div",S:"ytp-ce-website-metadata",va:b.metadata},{I:"a",Ka:["ytp-ce-website-goto","ytp-ce-link"],W:{href:N3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:M3(b)},{I:"div",S:"ytp-ce-expanding-icon",W:Yqb(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={I:"div",Ka:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.RD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",W:{dir:g.Jv(b.title||"")},va:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",va:b.metadata},{I:"a",Ka:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:N3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:M3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
va:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.Bv(c.element,"ytp-ce-placeholder");return c},M3=function(a){if(a.HX)var b=a.HX.thumbnails;
return Yqb(b?b[b.length-1].url:null)},Yqb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Xqb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;a.K>0?(g.Bv(b.element,"ytp-ce-force-expand"),O3(a,c.id,!0)):(g.Dv(b.element,"ytp-ce-force-expand"),g.Dv(b.element,"ytp-ce-element-hover"),O3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){Zqb(a,b,c)});
b.listen("mouseleave",function(){$qb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.Bv(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){arb(a,c,m)});
b.listen("keypress",function(m){arb(a,c,m)});
b.listen("focus",function(){Zqb(a,b,c)});
b.listen("blur",function(){$qb(a,b,c)});
b.listen("touchstart",function(){Zqb(a,b,c)});
var l=g.wf("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Dv(b.element,"ytp-ce-element-hover");g.Dv(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=m.keyCode===9&&!m.shiftKey});
d(g.wf("ytp-sb-subscribe",b.element));d(g.wf("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},arb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.Av(d,"ytp-ce-element");){g.Av(d,"subscribe-label")&&brb(a,b);
if(g.Av(d,"ytp-ce-channel-subscribe"))return;d=g.Nf(d)}if(!d||g.Av(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])$qb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.Jea==="new")brb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.je(N3(a,b.targetUrl)),c=g.de(c),g.LF(c,void 0,b.sessionData);else{var e=g.zR(a.player.U())||a.player.getVideoData().Kf,f=function(){var h=N3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.jA(h);e&&n&&
(n.v||n.list)?a.player.jp(n.v,l,n.list,!1,void 0,m||void 0):g.Mza(h,l)};
brb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},N3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.HR(a)+b}else return"";return b},Zqb=function(a,b,c){g.Av(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.Bv(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.uv(function(){g.Bv(b.element,"ytp-ce-element-hover")},200)).start():g.Bv(b.element,"ytp-ce-element-hover"),P3(a,c.e$),O3(a,c.id,!0))},$qb=function(a,b,c){g.Dv(b.element,"ytp-ce-element-hover");
g.Dv(b.element,"ytp-ce-force-expand");O3(a,c.id,!1)},O3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.v(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Fv(a.j[e].element,"ytp-ce-element-shadow-show",c)},P3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||K3(a))c&&c();else{b=crb(a,b);var e=0,f=!1,h=new g.uv(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.UC(b[a],d)}},brb=function(a,b,c){P3(a,b.clickUrls,c);
(a=g.aE())&&b.p$&&g.uE(a,b.visualElement)},crb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(drb(b[d],c));return a},drb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},erb=function(a){return typeof a==="string"?a:""},Q3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},frb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},R3=function(a){return a.value?a.value:null},S3=function(a){if(!a)return null;
var b=g.je(erb(a.value));b=g.de(b);if(!b)return null;var c=Q3(a.target,grb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new frb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},hrb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},krb=function(a){if(!a)return null;
var b=Q3(a.type,irb),c=Q3(a.trigger,jrb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=S3(a?a:null);return b?new hrb(b,c,a):null},lrb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},mrb=function(a,b){return g.Cb(a.action,b)},nrb=function(a,b){this.context=a;
this.j=b},orb=function(a){return a.customMessage?T3("div","iv-card-message",a.customMessage):""},U3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",W:{style:a},V:c}},prb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.v(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(T3("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},T3=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Jv(c);return{I:a,W:b,va:c}},qrb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.dE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.dE+");");c.dir=g.Jv(a.customMessage);var d=[{I:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ka:b,W:c,V:d}},V3=function(a,b,c,d){if(d){b=g.v(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.jj.click,5)}},rrb=function(a,b){this.merchant=a;
this.price=b},srb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},trb=function(a,b){return b?b:srb(a)?"current":"new"},W3=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.qb=!1;this.Wa=new Map;this.bb=new Map;this.context.J.addEventListener(g.MI("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.NI("annotations_module"),function(d){(d=c.bb.get(d))&&d.apply(c)})},X3=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.WM(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.qb=!1});
a.context.j.listen(b,"touchmove",function(){a.qb=!0})},urb=function(a){var b;
return((b=g.V(a,g.VE))==null?0:b.url)?g.V(a,g.VE).url:(a=g.V(a,g.AS))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},Y3=function(a,b,c){return{iZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
E2:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
qM:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},vrb=function(a,b,c){W3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ab=this.Na=this.Lb=this.C=this.isInitialized=!1;this.cards=[];this.Bb=this.Z=this.La=this.G=this.Va=this.j=null;this.qa=[];this.ra=this.N=this.Hf=this.Ha=null;this.K=0;this.Fa=new g.uv(function(){},c.X.Ql?4E3:3E3);
g.L(this,this.Fa);this.gb=new g.uv(function(){});
g.L(this,this.gb);this.Ca=new nrb(c,function(e,f,h,l,m,n){X3(d,e,f,h,l,m,n)});
this.Y=new g.W({I:"div",S:"iv-drawer",W:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",W:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ka:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.L(this,this.Y);this.D=this.Y.element;this.Ya=new g.iF(this.Y,330);g.L(this,this.Ya);this.Kb=g.wf("iv-drawer-header-text",this.D);this.B=g.wf("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Lb&&Z3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Lb=d.C)&&$3(d)});
this.Sa=new g.GJ(this);g.L(this,this.Sa);this.J.addEventListener("videodatachange",this.Xt.bind(this))},wrb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){Z3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){$3(a)});
var c=b.headerText;g.Pf(a.Kb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ha=g.ZD(b.trackingParams);a.N=g.ZD(b.closeTrackingParams);a.Hf=g.ZD(b.iconTrackingParams)},xrb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.fb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.IE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,jj:{},Gp:null,Qj:e.trackingParams?g.ZD(e.trackingParams):null,Hf:f&&f.trackingParams?g.ZD(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
dE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};a4(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.IE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:b4(a,c,b,f),sponsored:!1,jj:Y3(f,e,f.command),Gp:f.trackingParams?g.ZD(f.trackingParams):null,Qj:e.trackingParams?g.ZD(e.trackingParams):null,Hf:l&&l.trackingParams?g.ZD(l.trackingParams):null,imageUrl:c4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.IE(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,dE:null,title:f.title?g.IE(f.title):"",customMessage:f.callToAction?g.IE(f.callToAction):"",url:g.V(f.command,g.VE).url?S3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(f.command,g.VE).url}):null,onClickCommand:null};a4(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.IE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:b4(a,c,b,e),sponsored:!1,jj:Y3(e,f,e.endpoint),Gp:e.trackingParams?g.ZD(e.trackingParams):null,Qj:f.trackingParams?g.ZD(f.trackingParams):null,Hf:l&&l.trackingParams?g.ZD(l.trackingParams):null,channelId:g.V(e.endpoint,g.PS).browseId,customMessage:e.customText?g.IE(e.customText):null,profileImageUrl:c4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.IE(e.channelName):"",metaInfo:[e.subscriberCountText?g.IE(e.subscriberCountText):""],url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(e.endpoint,g.PS).canonicalBaseUrl?g.V(e.endpoint,g.PS).canonicalBaseUrl:"/channel/"+g.V(e.endpoint,g.PS).browseId}),onClickCommand:null};a4(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.IE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:b4(a,c,b,e),sponsored:!1,jj:Y3(e,f,e.action),Gp:e.trackingParams?g.ZD(e.trackingParams):null,Qj:f.trackingParams?g.ZD(f.trackingParams):null,Hf:l&&l.trackingParams?g.ZD(l.trackingParams):null,FH:c4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.IE(e.customMessage):null,playlistVideoCount:g.IE(e.playlistVideoCount),title:e.playlistTitle?g.IE(e.playlistTitle):"",metaInfo:[e.channelName?g.IE(e.channelName):
"",e.videoCountText?g.IE(e.videoCountText):""],url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:urb(e.action)}),onClickCommand:null};a4(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.IE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:b4(a,c,b,e),sponsored:!1,jj:Y3(e,f,e.action),Gp:e.trackingParams?g.ZD(e.trackingParams):null,Qj:f.trackingParams?g.ZD(f.trackingParams):null,Hf:l&&l.trackingParams?g.ZD(l.trackingParams):null,FH:c4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.IE(e.lengthString):null,customMessage:e.customMessage?g.IE(e.customMessage):null,title:e.videoTitle?g.IE(e.videoTitle):"",metaInfo:[e.channelName?g.IE(e.channelName):
"",e.viewCountText?g.IE(e.viewCountText):""],isLiveNow:!!e.badge,url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:urb(e.action)}),onClickCommand:null};a4(a,b)}}}}}a.K++},c4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},b4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},zrb=function(a,b){if(b=yrb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.Bf.id),g.Mf(b.oO),g.Gb(a.cards,b),a.II(),d4(a)},Z3=function(a,b,c){if(!a.C){a.Ya.show();
a.Va=new g.uv(function(){g.Bv(a.context.J.getRootNode(),g.xY.IV_DRAWER_OPEN)},0);
a.Va.start();a.Sa.T(a.B,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.aE();d&&a.Ha&&a.N&&g.sE(d,[a.Ha,a.N]);b={TRIGGER_TYPE:b};for(var e=g.v(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.e_||(f.e_=!0,Arb(a.context.logger,f.Bf.jj.iZ,b)),d&&g.sE(d,[f.Bf.Gp]);B3(a.J);c&&(a.G=new g.uv(function(){a.La=a.Z;a.Bb.focus()},330),a.G.start())}},$3=function(a){a.C&&(a.Ya.hide(),g.lB(a.Sa),g.Dv(a.context.J.getRootNode(),g.xY.IV_DRAWER_OPEN),a.C=!1,B3(a.J),a.G&&a.G.stop(),a.G=new g.uv(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},Brb=function(a){g.Cv(a.Jb(),
[g.xY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.ET(a.J,a.D,5);a.TD();a.Z=g.wf("ytp-cards-button",a.J.getRootNode());a.Bb=g.wf("iv-drawer-close-button",a.D);a.isInitialized=!0},Crb=function(a){a.qa.push(g.hD("iv-teaser-shown",a.e5,a));
a.qa.push(g.hD("iv-teaser-hidden",a.J$,a));a.qa.push(g.hD("iv-teaser-clicked",a.d5,a));a.Ab=!0},Drb=function(a,b){var c;
return b.onClickCommand&&((c=g.V(b.onClickCommand,g.cnb))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.ra=b,!0):!1},Erb=function(a,b){a.ra=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.FWa(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.V(h[0],g.g4a))==null?void 0:d.timeRangeStartMillis)||0,a.ra=null,!0}return!1},a4=function(a,b){if(!Drb(a,b)||Erb(a,b)){var c=Frb(a,b);
if(c){var d={Bf:b,oO:c.element,e_:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Ab||Crb(a),zrb(a,b.id),c=a.findLastIndex(d),g.Nb(a.cards,c,0,d));else{a.isInitialized||Brb(a);zrb(a,b.id);var e=a.findLastIndex(d);g.Nb(a.cards,e,0,d);c.Ja(a.B,e);a.II()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,d4(a),Grb(a,d),Z3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.J.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&Hrb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){Hrb(a,d)}),d4(a))}}},Frb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",va:b.displayDomain}:void 0;var d=qrb(b);c={I:"div",Ka:["iv-card"],V:[{I:"a",S:"iv-click-target",W:{href:b.url?R3(b.url)||"":""},V:[U3(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[T3("h2",void 0,b.title),d]}]}]};c=new g.W(c);V3(a,g.vf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-channel"],V:[{I:"a",Ka:["iv-click-target"],W:{href:R3(b.url)||"","data-ytid":b.channelId},V:[U3(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[orb(b),{I:"h2",S:"iv-card-primary-link",va:b.title},prb(b)]}]}]};c=new g.W(c);V3(a,g.vf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",Ka:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",W:{href:R3(b.url)||""},V:[U3(b.FH,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[orb(b),T3("h2","iv-card-primary-link",b.title),prb(b)]}]}]};
c=new g.W(c);V3(a,g.vf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=b.offers.length!=0;c=["iv-card"];d="";var f=qrb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",va:f.merchant}),f={I:"div",V:e});e=b.url?R3(b.url)||"":"";c={I:"div",Ka:c,W:{tabindex:"0"},V:[{I:"a",Ka:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",va:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",W:{href:e},V:[T3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.Bf("span");g.Pf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Gd(d,"adInfo");V3(a,g.vf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",va:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ka:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null;e={I:"div",Ka:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",W:{href:((c=b.url)==null?void 0:R3(c))||""},V:[U3(b.FH,d),{I:"div",S:"iv-card-content",V:[orb(b),T3("h2","iv-card-primary-link",b.title),prb(b),f]}]}]};c=new g.W(e);V3(a,g.vf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Irb=function(a){if(a.j)return a.j.Bf.type==="productListing";
if(a.J.L("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.ds(a.cards,function(c){return c.Bf.type==="productListing"})}return g.ds(a.cards,function(c){return c.Bf.type==="productListing"})},d4=function(a){g.Fv(a.J.getRootNode(),"ytp-cards-shopping-active",Irb(a))},Hrb=function(a,b){if(!g.Av(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.aE(),d=a.j?a.j.Bf.Hf:a.Hf;
c&&d&&g.tE(c,[d]);a.j=b;d4(a)}(c=a.isInitialized&&a.Jb().style.display=="none")||(c=a.context.J.getPlayerState(),d=c===0&&a.context.J.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.Bf.teaserDurationMs&&a.J.fC(!0,{teaserText:b.Bf.teaserText,durationMs:b.Bf.teaserDurationMs,onClickCommand:b.Bf.onClickCommand});a.gb.isActive()||((!a.C||!a.Fa.isActive()&&a.Na)&&Grb(a,b),a.gb.start(910+b.Bf.teaserDurationMs))}},Grb=function(a,b){a.Y.Ib?(b=new G3([0,
a.B.scrollTop],[0,b.oO.offsetTop],600,Oqb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.EE(a.Y,!0),a.B.scrollTop=b.oO.offsetTop,g.EE(a.Y,!1))},e4=function(a){return a.j&&a.j.Bf?a.j.Bf:a.cards[0]&&a.cards[0].Bf?a.cards[0].Bf:null},yrb=function(a,b){return g.Cb(a.cards,function(c){return c.Bf.id===b})},f4=function(a,b,c){W3.call(this,a,b);
this.annotation=c;this.isActive=!1},Jrb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},g4=function(a,b,c){f4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Krb=function(a,b){var c=c===void 0?0:c;
var d=Fqb(b).width;g.Ss(b,d);c=new Mqb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Nqb);g.L(a,c);a.context.C.listen(c,"begin",function(){g.Ys(b,!0)});
c.play()},Nrb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ka:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({I:"div",Ka:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.UV(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ja(d));var f=a.createElement({I:"div",Ka:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ka:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Ys(h,!1);var l=a.createElement({I:"div",Ka:["branding-context-container-outer"]});l.appendChild(h);g.Ls(l,"right",b.image_width+"px");g.Ff(a.Jb(),l);a.C=new g.uv(function(){Lrb(a,h,l)},500);
g.L(a,a.C);a.context.j.listen(a.Jb(),"mouseover",function(){Mrb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Jb(),"mouseout",function(){a.C.start()})}},Mrb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Xs(b);a.j||(b.style.width=g.Rs(f.width,!0),c.style.width=g.Rs(f.width,!0));g.Ls(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Ls(d,"right","1px");a.D=!0;g.Ys(b,!0);a.G=new g.uv(function(){g.Bv(this.Jb(),"iv-branding-active")},0,a);
a.G.start()}},Lrb=function(a,b,c){g.Dv(a.Jb(),"iv-branding-active");
a.K=new g.uv(function(){g.Ys(b,!1);a.j||(c.style.width=g.Rs(0,!0))},250);
a.K.start();a.D=!1},Orb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Prb=function(a,b,c){f4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ka:["iv-promo-contents"]});this.G=new g.uv(function(){d.j.setAttribute("aria-hidden","true");g.Ys(d.C,!1);g.Ys(d.B,!0)},700,this);
g.L(this,this.G)},Srb=function(a,b,c){c.stopPropagation();
Qrb(a);Rrb(a,b);a.j.focus()},Trb=function(a){a.isCollapsed||a.Z||a.D||(g.Bv(a.Jb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Qrb=function(a){a.G.stop();
a.isCollapsed&&(g.Ev(a.Jb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Ys(a.B,!1),g.Ys(a.C,!0))},Rrb=function(a,b){a.D||(a.D=g.ng(function(){Urb(this);
Trb(this)},b,a))},Urb=function(a){a.D&&(g.Ua.clearTimeout(a.D),a.D=null)},Vrb=function(a){this.J=a},Arb=function(a,b,c){b&&(c?h4(a,b.map(function(d){return g.Wu(d,c)})):h4(a,b))},h4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.v(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.UC(m,f);d&&(e++,d!==0&&a.J.sendVideoStatsEngageEvent(d,f))},Wrb=function(a){g.dV.call(this,a);
var b=this;this.qa=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new Vrb(this.player);this.D=new g.GJ(this);this.G=this.N=null;this.events=new g.GJ(this);this.Zg=this.Y=this.j=null;this.ra=[];g.L(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.f5,this);this.subscribe("resize",this.iL,this);this.player.U().Na.subscribe("vast_info_card_add",this.v0,this);g.L(this,this.events);this.Ca=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.W({I:"div",Ka:["ytp-player-content","ytp-iv-player-content"]});g.L(this,this.B);g.ET(this.player,this.B.element,4);this.B.hide();this.C=new g.W({I:"div",Ka:["ytp-iv-video-content"]});g.L(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Ca);this.C.element.appendChild(a);this.bv()&&this.load();var c=this.createElement({I:"style"});(g.of("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Mf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Xrb=function(a){a=a.createElement({I:"div",
Ka:["annotation","annotation-type-custom"]});g.Ys(a,!1);return a},Yrb=function(a,b){b=!b.isCued()&&!g.pF(b,1024);
g.EE(a.B,b);g.EE(a.C,b)},Zrb=function(a,b,c){a.Z=!0;
a.G=g.yA(b,c)},$rb=function(a,b){for(var c={},d=g.v(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.db(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push($rb(a,e))}return c},dsb=function(a){var b=a.player.getVideoData();
if(b.Wa){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.rA(h)&&h.responseXML?h.responseXML:null)&&asb(a,h)}};
g.EB()&&(d.onFinish=bsb(a,d.onFinish));d.postParams={ic_only:"1"};csb(d,c);a.Z=!0;g.yA(b.Wa,d)}}},csb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.NI&&(a.postParams.ic_coll=b.NI);b.pO&&(a.postParams.ic_xml=b.pO);b.vM&&(a.postParams.ic_track=b.vM)},esb=function(a){var b=new g.W({I:"div"});
g.Ys(b.element,!1);var c=new vrb(a.player,b.element,i4(a));g.L(c,b);b.Ja(a.B.element);c.pH();return c},gsb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.qa=!0,fsb(a,b),b.headerText&&a.Zg&&(c=g.IE(b.headerText),a.Zg.setAttribute("title",c))},i4=function(a){if(!a.Y){var b=new Pqb(a);
g.L(a,b);var c=new g.Aq(a);g.L(a,c);a.Y=new Orb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Bj)}return a.Y},asb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.aE();if(e){var f=g.$D();f&&g.eA(g.kya)(void 0,e,f,[g.ZD(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=$rb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=Q3(f.type,hsb),p=Q3(f.style,isb),q=erb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=krb;if(t==null)var u=null;else if(g.bb(t)){l=[];for(var w=g.v(t),A=w.next();!A.done;A=w.next()){var C=f(A.value);
C&&l.push(C)}u=l}else{var F=f(t);u=F?[F]:[]}e=m&&n?new lrb(m,n,p,u,r):null}else e=null}catch(na){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=Xrb(f),M=null;switch(l.type){case "branding":if(f.player.U().Hd)break;f.B.element.appendChild(H);M=new g4(H,i4(f),l);break;case "promotion":g.ET(f.player,H,4),M=new Prb(H,i4(f),l)}M&&M.pH();if(f=M)g.L(a,f),a.K[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=esb(a),g.L(a,a.j));if(e.type==="card"){H=a.j;var N=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(N)switch(f=e.tracking||{},f={iZ:f.impression,click:f.click,close:f.close,E2:f.teaser_impression,qM:f.teaser_click},l=e.tracking_params||{},M=null,N){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,Gp:l.card?g.ZD(l.card):null,Qj:l.teaser?g.ZD(l.teaser):null,Hf:l.icon?g.ZD(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:S3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};a4(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,
Gp:l.card?g.ZD(l.card):null,Qj:l.teaser?g.ZD(l.teaser):null,Hf:l.icon?g.ZD(l.icon):null,FH:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:S3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};a4(H,c);break;case "productListing":e.signin_url&&(M=S3({target:"current",value:e.signin_url}));N=[];for(var Q=e.offers||[],da=0;da<Q.length;da++)N.push(new rrb(g.cf(Q[da].merchant),
g.cf(Q[da].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,Gp:l.card?g.ZD(l.card):null,Qj:l.teaser?g.ZD(l.teaser):null,Hf:l.icon?g.ZD(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,dE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:S3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),psb:M,osb:e.signin_title?e.signin_title:void 0,nsb:e.signin_message?e.signin_message:void 0,offers:N,onClickCommand:null};a4(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,Gp:l.card?g.ZD(l.card):
null,Qj:l.teaser?g.ZD(l.teaser):null,Hf:l.icon?g.ZD(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,dE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:S3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};a4(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,Gp:l.card?g.ZD(l.card):null,Qj:l.teaser?g.ZD(l.teaser):null,Hf:l.icon?g.ZD(l.icon):null,FH:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:S3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},a4(H,c)}}else wrb(a.j,e);c=!0}}c&&
(B3(a.player),a.iL())},fsb=function(a,b){var c=!1;
a.j||(a.j=esb(a),g.L(a,a.j));for(var d=g.v(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(xrb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.WS(f)||(c=a.j,d=b.headerText?g.IE(b.headerText):"",g.Pf(c.Kb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ha=b.trackingParams?g.ZD(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.ZD(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Hf=b.icon.infoCardIconRenderer.trackingParams?g.ZD(b.icon.infoCardIconRenderer.trackingParams):null,a.iL());B3(a.player)}},jsb=function(a,b,c,d,e){if(!a.player.U().Hd){var f=[];
b.navigationEndpoint&&g.V(b.navigationEndpoint,g.PS)&&g.V(b.navigationEndpoint,g.PS).browseId&&f.push(new hrb("openUrl","click",new frb("/channel/"+g.V(b.navigationEndpoint,g.PS).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.V(b.subscribeButton,
g.QS)){d.channel_id=g.V(b.subscribeButton,g.QS).channelId;var l;b=g.V(b.subscribeButton,g.QS);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.IE(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.IE(b.subscriberCountText))):(b.subscriberCountText&&(e=g.IE(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.IE(b.subscriberCountWithSubscribeText)));var m,n=((m=g.V((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.u2))==null?void 0:m.url)||"";l={subscribeText:g.IE(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.IE(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new lrb(c,"branding","branding",f,d);l=Xrb(a);a.B.element.appendChild(l);f=new g4(l,i4(a),f);f.pH();g.L(f,f);a.K[c]=f}},bsb=function(a,b){return function(){var c=g.Ja.apply(0,arguments);
a.Ma()||a.ra.push(g.gv.Si(function(){b.apply(null,g.ra(c))}))}},ksb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.xT.prototype.fC=g.ca(28,function(a,b){var c=g.CV(this.zb());c&&c.fC(a,b)});
var D3={},E3=null;g.lb(G3,g.Gv);g.k=G3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;F3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.aL();this.Ln("play");this.isPaused()&&this.Ln("resume");this.j=1;var b=g.fb(this);b in D3||(D3[b]=this);Iqb();Jqb(this,a);return!0};
g.k.stop=function(a){F3(this);this.j=0;a&&(this.progress=1);Kqb(this,this.progress);this.onStop();this.qs()};
g.k.pause=function(){this.isPlaying()&&(F3(this),this.j=-1,this.Ln("pause"))};
g.k.xa=function(){this.j==0||this.stop(!1);this.Ln("destroy");G3.Qf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.VM=function(){this.Ln("animate")};
g.k.Ln=function(a){this.dispatchEvent(new Lqb(a,this))};
g.lb(Lqb,g.yb);g.lb(H3,G3);H3.prototype.C=function(){};
H3.prototype.VM=function(){this.C();H3.Qf.VM.call(this)};
H3.prototype.qs=function(){this.C();H3.Qf.qs.call(this)};
H3.prototype.aL=function(){this.C();H3.Qf.aL.call(this)};
g.lb(Mqb,H3);Mqb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.x(Pqb,g.I);g.k=Pqb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=g.fB(a,b,c);this.j.push(a);return a};
g.k.OF=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=Gqb(a,b,c);this.j.push(a);return a};
g.k.Qc=function(a){g.gB(a);g.Gb(this.j,a)};
g.k.removeAll=function(){g.gB(this.j);this.j.length=0};
g.k.xa=function(){this.removeAll();g.I.prototype.xa.call(this)};g.x(Sqb,g.dV);g.k=Sqb.prototype;g.k.load=function(){g.dV.prototype.load.call(this);if(!K3(this)){var a=g.iYa(this.player.getVideoData());a?(a=Rqb(a,Tqb(this)),L3(this,a,!1)):Uqb(this)}};
g.k.unload=function(){L3(this,null);this.C&&(this.C.abort(),this.C=null);g.dV.prototype.unload.call(this)};
g.k.Uh=function(a,b){return K3(this)?a==="loadCustomEndscreenRenderer"?(a=Rqb(b,"new"),L3(this,a),!0):null:null};
g.k.getOptions=function(){return K3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.lc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<lsb.length;f++){var h=Math.abs(b.width-lsb[f]);if(e===-1||d>=h)e=f,d=h}d=msb[e];this.B&&g.Ls(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Ws(e.element,m,f);g.Ss(e.element,n,p);g.Ev(e.element,nsb);m>256||f>256?g.Bv(e.element,"ytp-ce-large-round"):m>96||f>96?g.Bv(e.element,"ytp-ce-medium-round"):g.Bv(e.element,"ytp-ce-small-round");g.Ev(e.element,osb);m=h.left+h.width/2;h=h.top+l/2;g.Bv(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Ev(e.element,msb);g.Bv(e.element,d);(e=g.pf(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Ls(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")P3(this,this.endscreen.impressionUrls),(a=g.aE())&&this.endscreen.visualElement&&g.rE(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Bv(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Bv(b,"ytp-ce-shown");P3(this,c.impressionUrls);(b=g.aE())&&g.rE(b,c.visualElement);this.player.U().N&&this.player.ib("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.Dv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Dv(b,"ytp-ce-shown");this.player.U().N&&this.player.ib("endscreenelementhidden",a)}};
g.k.Qca=function(a){var b=this;a.target===window&&(new g.uv(function(){for(var c=g.v(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Ev(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var lsb=[346,426,470,506,570,640,853,1280,1920],msb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),osb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],nsb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var grb={Swa:"current",nYa:"new"};var irb={CLOSE:"close",f1a:"openUrl",SUBSCRIBE:"subscribe"},jrb={dva:"click",CLOSE:"close",cJa:"hidden",n7a:"rollOut",o7a:"rollOver",i9a:"shown"};lrb.prototype.De=function(){var a=mrb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var isb={qpa:"anchored",W3:"branding",CHANNEL:"channel",Iwa:"cta",fJa:"highlightText",mNa:"label",PLAYLIST:"playlist",POPUP:"popup",vbb:"speech",SUBSCRIBE:"subscribe",jfb:"title",VIDEO:"video",Rmb:"website"},hsb={W3:"branding",Fsa:"card",Qya:"drawer",eJa:"highlight",ETa:"marker",x5a:"promotion",TEXT:"text",wob:"widget"};g.x(W3,g.I);g.k=W3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.LI(a,b,{id:c,namespace:"annotations_module"});d&&this.Wa.set(a,d);e&&this.bb.set(a,e);this.context.J.mf([a])};
g.k.pH=function(){this.context.B.subscribe("resize",this.II,this)};
g.k.Jb=function(){return this.element};
g.k.WM=function(a,b,c,d,e,f){if(this.qb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Mf(this.Jb())};
g.k.II=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=R3(a);if(f){var h=trb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Kf||!1,n=g.jA(f||"");m&&n&&(n.v||n.list)?e.context.J.jp(n.v,b,n.list,!1):g.LF(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);h4(this.context.logger,c,l,d);srb(f)||(c=g.aE(),d=b.itct,c&&d&&g.uE(c,g.ZD(d)))}};
g.k.xa=function(){this.Wa.clear();this.bb.clear();g.I.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.L(this,a);return a.element};g.x(vrb,W3);g.k=vrb.prototype;g.k.Xt=function(){this.ra&&a4(this,this.ra)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Xs(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.II=function(){var a=this.isAvailable();g.Ys(this.Jb(),a);g.Fv(this.context.J.getRootNode(),g.xY.IV_DRAWER_ENABLED,a);B3(this.J)};
g.k.destroy=function(){this.J.fC(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.iD(this.qa);g.lB(this.Sa);this.Va&&this.Va.dispose();this.G&&this.G.dispose();W3.prototype.destroy.call(this)};
g.k.TD=function(){var a=this,b=g.wf("iv-drawer-close-button",this.D);this.context.j.listen(b,"click",this.R7,this);this.context.j.listen(this.B,"touchend",function(){a.Fa.start()});
this.context.j.listen(this.B,"scroll",this.n8,this);this.context.B.subscribe("onHideControls",function(){a.Na=!0});
this.context.B.subscribe("onShowControls",function(){a.Na=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Av(a.J.getRootNode(),"ytp-autohide")});
this.qa.push(g.hD("iv-button-shown",this.I$,this));this.qa.push(g.hD("iv-button-hidden",this.H$,this));Crb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Db(this.cards,function(c){return a.Bf.startMs>c.Bf.startMs||a.Bf.startMs===c.Bf.startMs&&a.Bf.timestamp>=c.Bf.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.R7=function(){if(this.C){h4(this.context.logger,e4(this).jj.close);var a=g.aE();a&&this.N&&g.uE(a,this.N);$3(this)}};
g.k.n8=function(){g.Fv(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.I$=function(){var a=g.aE(),b=e4(this);b=b?b.Hf:this.Hf;a&&b&&g.sE(a,[b])};
g.k.H$=function(){var a=g.aE(),b=e4(this);b=b?b.Hf:this.Hf;a&&b&&g.tE(a,[b])};
g.k.e5=function(){var a=e4(this);h4(this.context.logger,a.jj.E2);var b=g.aE();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Qj&&c.push(a.Qj);a.Hf&&c.push(a.Hf);c.length>0&&g.sE(b,c)}else g.sE(b,[a.Qj,a.Hf])};
g.k.J$=function(){var a=g.aE(),b=e4(this);a&&b&&g.tE(a,[b.Qj])};
g.k.d5=function(a){var b=e4(this),c=g.aE();this.j?a?(a=this.context.logger,h4(a,b.jj.qM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Qj&&g.uE(c,b.Qj)):(a=this.context.logger,h4(a,b.jj.qM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Hf&&g.uE(c,b.Hf)):(a=this.context.logger,h4(a,b.jj.qM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Hf&&g.uE(c,this.Hf))};g.x(f4,W3);f4.prototype.pH=function(){W3.prototype.pH.call(this);Jrb(this)};
f4.prototype.show=function(){W3.prototype.show.call(this);var a=g.aE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.sE(a,[g.ZD(b.itct)])};
f4.prototype.hide=function(){W3.prototype.hide.call(this);var a=g.aE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.tE(a,[g.ZD(b.itct)])};g.x(g4,f4);
g4.prototype.vy=function(){g.Bv(this.Jb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ka:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ys(this.B,!1);var b=this.createElement({I:"button",Ka:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Jb().appendChild(b);var c=this.annotation.De();c&&X3(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||Nrb(this,
a)};
g4.prototype.show=function(){if(!this.isActive&&(f4.prototype.show.call(this),this.N||(this.vy(),this.N=!0),g.Ys(this.Jb(),!0),this.isActive=!0,this.B)){try{Krb(this,this.B)}catch(a){}g.Bv(this.context.J.getRootNode(),"ytp-branding-shown")}};
g4.prototype.hide=function(){this.isActive&&(f4.prototype.hide.call(this),g.Ys(this.Jb(),!1),this.isActive=!1,g.Dv(this.context.J.getRootNode(),"ytp-branding-shown"))};
g4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);f4.prototype.destroy.call(this)};g.x(Prb,f4);g.k=Prb.prototype;
g.k.vy=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Jb().setAttribute("aria-hidden","true");this.Jb().setAttribute("aria-label","Promotion");this.Jb().tabIndex=0;var e=this.annotation.De(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ka:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&X3(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Oe(f,R3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",va:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ka:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ka:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",va:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&X3(this,
this.Jb(),e,this.annotation.id,b.session_data,void 0,c)}g.Bv(this.j,"iv-click-target");e&&X3(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",va:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ka:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.Bv(this.j,"iv-click-target"),e&&X3(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ka:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.listen(this.B,"click",function(q){Srb(a,5E3,q)});
c.appendChild(this.B);g.Ys(this.B,!1);this.context.j.listen(this.Jb(),"mouseover",this.G9,this);this.context.j.listen(this.Jb(),"mouseout",this.F9,this);this.context.j.listen(this.Jb(),"touchend",function(q){Srb(a,5E3,q)});
this.C=this.createElement({I:"button",Ka:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.B9:this.A9,this);c.appendChild(this.C);g.Cv(this.Jb(),d);h&&(g.Ff(this.Jb(),h),n&&h.appendChild(n));g.Ff(this.Jb(),this.N);g.Ff(this.Jb(),c)};
g.k.show=function(){this.isActive||(f4.prototype.show.call(this),this.Y||(this.vy(),this.Y=!0),g.Ys(this.Jb(),!0),g.ng(function(){g.Dv(this.Jb(),"iv-promo-inactive")},100,this),this.Jb().removeAttribute("aria-hidden"),this.isActive=!0,Urb(this),Qrb(this),Rrb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Bv(this.Jb(),"iv-promo-inactive"),this.isActive=!1,this.Jb().setAttribute("aria-hidden","true"))};
g.k.WM=function(a,b,c,d,e,f){return this.isCollapsed?!1:f4.prototype.WM.call(this,a,b,c,d,e,f)};
g.k.G9=function(a){this.Z=!0;Srb(this,500,a)};
g.k.F9=function(){this.Z=!1;Trb(this)};
g.k.A9=function(a){a.stopPropagation();this.hide()};
g.k.B9=function(a){a.stopPropagation();Urb(this);this.isCollapsed=!0;g.Bv(this.Jb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();f4.prototype.destroy.call(this)};g.x(Wrb,g.dV);g.k=Wrb.prototype;g.k.Uh=function(a,b){if(!ksb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.$1(b))&&asb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(zrb(this.j,b),B3(this.player)),!0}return null};
g.k.getOptions=function(){return ksb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.bv=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.fT(b)||g.qT(this.player.app)?!1:c===1&&!b.HY||a.Na.get(b.videoId)||g.XS(b)||g.jYa(b)?!0:!1};
g.k.iL=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.Ws(this.C.element,a.width,a.height);g.Ss(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Vn();a=this.j;b=b.width;g.Fv(a.D,"iv-drawer-small",b<=426);g.Fv(a.D,"iv-drawer-big",b>=1280)}};
g.k.f5=function(a){Yrb(this,a.state);g.pF(a.state,2)&&(this.Wk()&&this.Dp()&&this.player.getPresentingPlayerType()!==2&&this.gC(!1),this.fC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.rA(h)&&h.responseXML?h.responseXML:null)&&(asb(b,h),g.Bv(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.dV.prototype.load.call(this);Yrb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.EB()&&(a=bsb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&csb(e,f);f=f&&(f.pO||f.NI);if(!c.Kv||f)c.Wa?Zrb(this,c.Wa,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.WS(h))&&!b.qa&&gsb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.ET(this.player,this.C.element,4);this.iL();(f=g.XS(c))&&fsb(this,f);(f=g.jYa(c))&&f.featuredChannel&&jsb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Zg=g.wf("ytp-cards-button",this.player.getRootNode());g.WS(c)&&gsb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Wa&&Zrb(this,b.Wa,a)};
g.k.unload=function(){this.player.tf("annotations_module");for(var a=g.v(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,B3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.qa=!1;this.K={};this.B.hide();g.dV.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.v0=function(a){a===this.player.getVideoData().videoId&&(this.loaded?dsb(this):this.load())};
g.k.Wk=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.qa};
g.k.Dp=function(){return!!this.j&&this.j.C};
g.k.gC=function(a,b,c){b=b===void 0?!1:b;this.Wk();this.j&&(a?c?Z3(this.j,c,b):Z3(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):$3(this.j))};
g.k.fC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.v0,this);g.Dv(this.player.getRootNode(),g.xY.IV_DRAWER_OPEN);for(var a=this.ra,b=g.gv,c=0,d=a.length;c<d;c++)b.Xj(a[c]);this.ra.length=0;g.dV.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.L(this,a);return a.element};g.cV("annotations_module",Wrb);g.cV("creatorendscreen",Sqb);})(_yt_player);
